inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Documentation:
    Enabled: false
