language: ruby
before_install: gem update --system
rvm:
- 2.2.2
script:
- bundle exec rake
notifications:
  email:
    recipients:
    - dlanileonardo@gmail.com
    on_success: never
    on_failure: change
addons:
  code_climate:
    repo_token: d4414bf80101ee909af5f04154416c9cccc5cd4c5d779c8a0f9aa2c4036cf68b
